# Generated by Django 2.2 on 2019-04-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
