# Generated by Django 2.2 on 2019-04-14 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 12, 24, 44, 554187), verbose_name='date published'),
        ),
    ]
