# Generated by Django 2.2 on 2019-04-15 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190414_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 19, 56, 48, 781203), verbose_name='date published'),
        ),
    ]
