# Generated by Django 2.2 on 2019-04-15 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190414_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 10, 24, 52, 735913), verbose_name='date published'),
        ),
    ]
