# Generated by Django 2.2 on 2019-04-25 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190415_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 21, 24, 23, 962948), verbose_name='date published'),
        ),
    ]
